# ----------------------------------------------- #
# Note: this file originates in template-node-lib #
# ----------------------------------------------- #

jobs: 5
ts: false
jsx: false
flow: false
coverage: true
browser: false
color: true
coverage-report: html
nyc-arg:
  - --exclude=dist
