# --------------------------------------------------------- #
# Note: this file originates in ahmadnassri/template-js-lib #
# --------------------------------------------------------- #

name: release

on:
  workflow_run:
    workflows: [ test ]
    branches: [ master ]
    types: [ completed ]

jobs:
  release:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    outputs:
      published: ${{ steps.release.outputs.published }}
      version: ${{ steps.release.outputs.release-version }}

    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: release-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run build

      - id: release
        uses: ahmadnassri/action-semantic-release@v1
        with:
          config: ${{ github.workspace }}/.semantic.json
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  mirror:
    needs: release

    timeout-minutes: 5

    runs-on: ubuntu-latest

    if: needs.release.outputs.published == 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: release-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci
      - run: npm run build

      - uses: ahmadnassri/action-github-registry-npm-proxy@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          scope: ${{ github.repository_owner }}


      - name: publish to github registry
        run: |
          npm version --no-git-tag-version v${{ needs.release.outputs.version }}
          npm publish
