# --------------------------------------------------------- #
# Note: this file originates in ahmadnassri/template-js-lib #
# --------------------------------------------------------- #

name: test

on: [ push, pull_request ]

env:
  NODE_ENV: test

jobs:
  deduplicate:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    # run on external PRs, but not on our internal PRs
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - run: echo ::info ::duplicate check ran successfully

  audit:
    timeout-minutes: 5

    needs: deduplicate

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3.4.1
      - uses: actions/checkout@v2
      - run: npm audit --audit-level=critical

  strategy:
    timeout-minutes: 5

    needs: deduplicate

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.parse.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2
      - id: parse
        run: echo "::set-output name=matrix::$(jq -c . < .github/matrix.json)"

  test:
    needs: [ strategy, audit ]

    timeout-minutes: 10

    name: ${{ matrix.name || format('node v{0} @ {1}', matrix.node-version, matrix.os) }}

    strategy:
      matrix: ${{ fromJSON(needs.strategy.outputs.matrix) }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/cache@v2.1.7
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ matrix.browser }}-${{ hashFiles('**/package-lock.json') }}

      - uses: microsoft/playwright-github-action@v1

      - run: npm ci
      - run: npm run test:ci
        env:
          BROWSER: ${{ matrix.browser }}
